version: 2

references:
  ## Cache
  cache_key: &cache_gradle_key
    key: ghd-gradle-{{ checksum "build.gradle" }}
  restore_cache: &restore_gradle_cache
    restore_cache:
      <<: *cache_gradle_key
  save_cache: &save_gradle_cache
    save_cache:
      <<: *cache_gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Docker image configurations
  docker_config: &docker_config
    working_directory: ~/ghd
    docker:
      - image: classmethod/techdoc-ja:1.0.2
    environment:
      TERM: dumb

jobs:
  checkout_code:
    <<: *docker_config
    steps:
      - checkout
      - save_cache:
          key: ghd-cache-{{ epoch }}
          paths:
            - ~/ghd

  build:
    <<: *docker_config
    steps:
      - restore_cache:
          key: ghd-cache
      - *restore_gradle_cache
      - run: pip -V || wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py
      - run: pip install -U pip
      - run:
          name: Gradle build (Documents)
          command: ./gradlew mkdocsBuild
      - *save_gradle_cache
      - save_cache:
          key: ghd-cache-build-{{ epoch }}
          paths:
            - ~/ghd
      # TODO: for Debug
      - store_artifacts:
          path: ~/ghd/build/mkdocs/

  deploy:
    <<: *docker_config
    steps:
      - restore_cache:
          key: ghd-cache-build
      - *restore_gradle_cache
      - run:
          command: ./gradlew mkdocksPublish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          # filters:
          #   branches:
          #     only: master
          requires:
            - build